services:
  # A Docker web service
  - type: web
    name: voice-assistant
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python fast_api_building.py
